# Generated by Django 4.2.30 on 2026-09-28 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('es_vigilancia_centinela', models.BooleanField(default=False, verbose_name='Vigilancia Centinela')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
                'db_table': 'especialidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Especialista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('cedula', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Cédula')),
                ('telefono', models.CharField(blank=True, default='', max_length=20, verbose_name='Teléfono')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='especialistas', to='morbilidades.especialidad', verbose_name='Especialidad')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='especialista_perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuario del Sistema')),
            ],
            options={
                'verbose_name': 'Especialista',
                'verbose_name_plural': 'Especialistas',
                'db_table': 'especialistas',
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_entrada', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Entrada')),
                ('hora_salida', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Salida')),
                ('pausa_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Inicio de Pausa')),
                ('pausa_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fin de Pausa')),
                ('total_horas', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Total Horas')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('especialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jornadas', to='morbilidades.especialista', verbose_name='Especialista')),
            ],
            options={
                'verbose_name': 'Jornada',
                'verbose_name_plural': 'Jornadas',
                'db_table': 'jornadas',
                'ordering': ['-fecha', '-hora_entrada'],
            },
        ),
        migrations.CreateModel(
            name='Morbilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('EMERGENCIA', 'Emergencia'), ('CONSULTA_ESPECIALISTA', 'Consulta por Especialista'), ('ECOSONOGRAMA', 'Ecosonograma'), ('NO_ASISTIDO', 'Paciente No Asistido')], max_length=30, verbose_name='Tipo de Módulo / Morbilidad')),
                ('diagnostico', models.TextField(blank=True, default='', verbose_name='Diagnóstico')),
                ('fecha_evento', models.DateField(verbose_name='Fecha del Evento')),
                ('motivo_consulta', models.TextField(blank=True, default='', verbose_name='Motivo de Consulta')),
                ('proxima_cita', models.DateField(blank=True, null=True, verbose_name='Próxima Cita')),
                ('codigo_emergencia', models.CharField(blank=True, default='', max_length=50, verbose_name='Código de Emergencia')),
                ('procedencia', models.CharField(blank=True, default='', max_length=150, verbose_name='Procedencia')),
                ('tipo_ecosonograma', models.CharField(blank=True, default='', max_length=150, verbose_name='Tipo de Ecosonograma')),
                ('planes', models.CharField(blank=True, default='', max_length=200, verbose_name='Planes / Tratamiento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('especialidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='morbilidades_por_especialidad', to='morbilidades.especialidad', verbose_name='Especialidad')),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='morbilidades_atendidas', to='morbilidades.especialista', verbose_name='Médico Atendiente')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='morbilidades', to='pacientes.paciente', verbose_name='Paciente')),
                ('usuario_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='morbilidades_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Morbilidad',
                'verbose_name_plural': 'Morbilidades',
                'db_table': 'morbilidades',
                'ordering': ['-fecha_evento', '-created_at'],
                'indexes': [models.Index(fields=['paciente'], name='morbilidade_pacient_cc61f3_idx'), models.Index(fields=['tipo_movimiento'], name='morbilidade_tipo_mo_54846f_idx'), models.Index(fields=['fecha_evento'], name='morbilidade_fecha_e_836f1a_idx'), models.Index(fields=['activo', '-fecha_evento'], name='morbilidade_activo_7ae6fb_idx'), models.Index(fields=['especialidad'], name='morbilidade_especia_df08ad_idx')],
            },
        ),
        migrations.CreateModel(
            name='EstadisticaEspecialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pacientes', models.IntegerField(default=0, verbose_name='Total Pacientes')),
                ('mes', models.IntegerField(verbose_name='Mes')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas', to='morbilidades.especialidad', verbose_name='Especialidad')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas', to='morbilidades.especialista', verbose_name='Médico')),
            ],
            options={
                'verbose_name': 'Estadística por Especialidad',
                'verbose_name_plural': 'Estadísticas por Especialidad',
                'db_table': 'estadisticas_especialidad',
                'ordering': ['-anio', '-mes'],
                'unique_together': {('especialidad', 'medico', 'mes', 'anio')},
            },
        ),
    ]
