# Generated by Django 4.2.30 on 2026-09-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morbilidades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='morbilidad',
            name='morbilidade_tipo_mo_54846f_idx',
        ),
        migrations.RemoveField(
            model_name='morbilidad',
            name='tipo_movimiento',
        ),
        migrations.AddField(
            model_name='morbilidad',
            name='tipo_modulo',
            field=models.CharField(choices=[('EMERGENCIA', 'Emergencia'), ('CONSULTA_ESPECIALISTA', 'Consulta por Especialista'), ('ECOSONOGRAMA', 'Ecosonograma'), ('NO_ASISTIDO', 'Paciente No Asistido')], default='EMERGENCIA', max_length=30, verbose_name='Tipo de Módulo'),
        ),
        migrations.AddIndex(
            model_name='morbilidad',
            index=models.Index(fields=['tipo_modulo'], name='morbilidade_tipo_mo_6ff623_idx'),
        ),
    ]
