services:
  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: siceme
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    restart: always

  web:
    build: .
    volumes:
      - .:/app
    ports:
      # Si WEB_PORT no está definido en .env, usa el 8000 por defecto
      - "${WEB_PORT:-8000}:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  db_data:
