# Generated by Django 4.2.30 on 2026-09-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20, unique=True, verbose_name='Cédula')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Sexo')),
                ('telefono', models.CharField(blank=True, default='', max_length=20, verbose_name='Teléfono')),
                ('dependencia', models.CharField(blank=True, default='', max_length=150, verbose_name='Dependencia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'pacientes',
                'ordering': ['nombre_completo'],
                'indexes': [models.Index(fields=['cedula'], name='pacientes_cedula_bddcda_idx'), models.Index(fields=['nombre_completo'], name='pacientes_nombre__e5c930_idx'), models.Index(fields=['activo', '-created_at'], name='pacientes_activo_4b608d_idx')],
            },
        ),
    ]
