# Generated by Django 5.2.9 on 2026-02-18 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('es_vigilancia_centinela', models.BooleanField(default=False, verbose_name='Vigilancia Centinela')),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
                'db_table': 'especialidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EstadisticaEspecialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pacientes', models.IntegerField(default=0, verbose_name='Total Pacientes')),
                ('mes', models.IntegerField(verbose_name='Mes')),
                ('anio', models.IntegerField(verbose_name='Año')),
            ],
            options={
                'verbose_name': 'Estadística por Especialidad',
                'verbose_name_plural': 'Estadísticas por Especialidad',
                'db_table': 'estadisticas_especialidad',
                'ordering': ['-anio', '-mes'],
            },
        ),
        migrations.CreateModel(
            name='Especialista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('telefono', models.CharField(blank=True, default='', max_length=20, verbose_name='Teléfono')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='especialistas', to='especialistas.especialidad', verbose_name='Especialidad')),
            ],
            options={
                'verbose_name': 'Especialista',
                'verbose_name_plural': 'Especialistas',
                'db_table': 'especialistas',
                'ordering': ['nombre_completo'],
            },
        ),
    ]
