# Generated by Django 5.2.9 on 2026-02-18 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('especialistas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='especialista',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='especialista_perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuario del Sistema'),
        ),
        migrations.AddField(
            model_name='estadisticaespecialidad',
            name='especialidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas', to='especialistas.especialidad', verbose_name='Especialidad'),
        ),
        migrations.AddField(
            model_name='estadisticaespecialidad',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas', to='especialistas.especialista', verbose_name='Médico'),
        ),
        migrations.AlterUniqueTogether(
            name='estadisticaespecialidad',
            unique_together={('especialidad', 'medico', 'mes', 'anio')},
        ),
    ]
