# Generated by Django 4.2.28 on 2026-03-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialistas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialista',
            name='cedula',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Cédula'),
        ),
    ]
