# Generated by Django 4.2.28 on 2026-04-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialistas', '0003_especialista_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidad',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='especialista',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
