# Generated by Django 5.2.9 on 2026-02-18 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MorbilidadEcosonograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido', models.CharField(max_length=200, verbose_name='Nombre y Apellido')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Sexo')),
                ('cedula', models.CharField(max_length=20, verbose_name='Cédula')),
                ('procedencia', models.CharField(blank=True, default='', max_length=150, verbose_name='Procedencia')),
                ('tipo_eco', models.CharField(max_length=150, verbose_name='Tipo de Ecosonograma')),
                ('numero_cedula', models.CharField(blank=True, default='', max_length=20, verbose_name='Número de Cédula')),
                ('diagnostico', models.TextField(verbose_name='Diagnóstico')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('planes', models.CharField(blank=True, default='', max_length=200, verbose_name='Planes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Ecosonograma',
                'verbose_name_plural': 'Ecosonogramas',
                'db_table': 'morbilidad_ecos',
                'ordering': ['-created_at'],
            },
        ),
    ]
