# Generated by Django 5.2.9 on 2026-02-18 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ecosonogramas', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='morbilidadecosonograma',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecosonogramas_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
    ]
