# Generated by Django 4.2.28 on 2026-02-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecosonogramas', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morbilidadecosonograma',
            name='medico',
            field=models.CharField(max_length=150, verbose_name='Médico'),
        ),
    ]
