# Generated by Django 4.2.28 on 2026-03-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecosonogramas', '0004_alter_morbilidadecosonograma_medico'),
    ]

    operations = [
        migrations.AddField(
            model_name='morbilidadecosonograma',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
