# Generated by Django 4.2.28 on 2026-04-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecosonogramas', '0005_morbilidadecosonograma_activo'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='morbilidadecosonograma',
            index=models.Index(fields=['activo', '-created_at'], name='morbilidad__activo_c516e6_idx'),
        ),
        migrations.AddIndex(
            model_name='morbilidadecosonograma',
            index=models.Index(fields=['activo', 'fecha'], name='morbilidad__activo_9a1d18_idx'),
        ),
    ]
