# Generated by Django 5.2.9 on 2026-02-18 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MorbilidadEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20, verbose_name='Cédula')),
                ('nombre_apellido', models.CharField(max_length=200, verbose_name='Nombre y Apellido')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Sexo')),
                ('dependencia', models.CharField(blank=True, default='', max_length=150, verbose_name='Dependencia')),
                ('telefono', models.CharField(blank=True, default='', max_length=20, verbose_name='Teléfono')),
                ('codigo', models.CharField(blank=True, default='', max_length=50, verbose_name='Código')),
                ('fecha_diagnostico', models.DateField(verbose_name='Fecha de Diagnóstico')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Morbilidad Emergencia',
                'verbose_name_plural': 'Morbilidades Emergencias',
                'db_table': 'morbilidad_emergencias',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MorbilidadEspecialista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido', models.CharField(max_length=200, verbose_name='Nombre y Apellido')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Sexo')),
                ('motivo_consulta', models.TextField(verbose_name='Motivo de Consulta')),
                ('diagnostico', models.TextField(verbose_name='Diagnóstico')),
                ('proxima_cita', models.DateField(blank=True, null=True, verbose_name='Próxima Cita')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Morbilidad Especialista',
                'verbose_name_plural': 'Morbilidades Especialistas',
                'db_table': 'morbilidad_especialistas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PacienteNoAsistido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Sexo')),
                ('fecha_cita', models.DateField(verbose_name='Fecha de Cita')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Paciente No Asistido',
                'verbose_name_plural': 'Pacientes No Asistidos',
                'db_table': 'pacientes_no_asistidos',
                'ordering': ['-created_at'],
            },
        ),
    ]
