# Generated by Django 5.2.9 on 2026-02-18 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emergencias', '0001_initial'),
        ('especialistas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='morbilidademergencia',
            name='especialidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emergencias', to='especialistas.especialidad', verbose_name='Especialidad'),
        ),
        migrations.AddField(
            model_name='morbilidademergencia',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emergencias', to='especialistas.especialista', verbose_name='Médico'),
        ),
    ]
