# Generated by Django 5.2.9 on 2026-02-18 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emergencias', '0002_initial'),
        ('especialistas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='morbilidademergencia',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergencias_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='morbilidadespecialista',
            name='especialidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='morbilidades_especialista', to='especialistas.especialidad', verbose_name='Especialidad'),
        ),
        migrations.AddField(
            model_name='morbilidadespecialista',
            name='especialista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='morbilidades', to='especialistas.especialista', verbose_name='Especialista'),
        ),
        migrations.AddField(
            model_name='morbilidadespecialista',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='morbilidades_esp_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='pacientenoasistido',
            name='especialidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='no_asistidos', to='especialistas.especialidad', verbose_name='Especialidad'),
        ),
        migrations.AddField(
            model_name='pacientenoasistido',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='no_asistidos', to='especialistas.especialista', verbose_name='Médico'),
        ),
        migrations.AddField(
            model_name='pacientenoasistido',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='no_asistidos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddIndex(
            model_name='morbilidademergencia',
            index=models.Index(fields=['especialidad'], name='morbilidad__especia_c5ef41_idx'),
        ),
        migrations.AddIndex(
            model_name='morbilidademergencia',
            index=models.Index(fields=['fecha_diagnostico'], name='morbilidad__fecha_d_8b5259_idx'),
        ),
        migrations.AddIndex(
            model_name='morbilidadespecialista',
            index=models.Index(fields=['especialidad'], name='morbilidad__especia_0b999c_idx'),
        ),
    ]
