# Generated by Django 4.2.28 on 2026-02-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencias', '0003_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='morbilidademergencia',
            new_name='morbilidad__especia_aa4777_idx',
            old_name='morbilidad__especia_c5ef41_idx',
        ),
        migrations.RenameIndex(
            model_name='morbilidadespecialista',
            new_name='morbilidad__especia_0db674_idx',
            old_name='morbilidad__especia_0b999c_idx',
        ),
        migrations.AlterField(
            model_name='morbilidademergencia',
            name='especialidad',
            field=models.CharField(max_length=150, verbose_name='Especialidad'),
        ),
        migrations.AlterField(
            model_name='morbilidademergencia',
            name='medico',
            field=models.CharField(max_length=150, verbose_name='Médico'),
        ),
        migrations.AlterField(
            model_name='morbilidadespecialista',
            name='especialidad',
            field=models.CharField(max_length=150, verbose_name='Especialidad'),
        ),
        migrations.AlterField(
            model_name='morbilidadespecialista',
            name='especialista',
            field=models.CharField(max_length=150, verbose_name='Especialista'),
        ),
        migrations.AlterField(
            model_name='pacientenoasistido',
            name='especialidad',
            field=models.CharField(max_length=150, verbose_name='Especialidad'),
        ),
        migrations.AlterField(
            model_name='pacientenoasistido',
            name='medico',
            field=models.CharField(max_length=150, verbose_name='Médico'),
        ),
    ]
