# Generated by Django 4.2.28 on 2026-03-03 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emergencias', '0004_rename_morbilidad__especia_c5ef41_idx_morbilidad__especia_aa4777_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='morbilidademergencia',
            name='morbilidad__especia_aa4777_idx',
        ),
        migrations.RemoveField(
            model_name='morbilidademergencia',
            name='especialidad',
        ),
    ]
