# Generated by Django 4.2.28 on 2026-03-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencias', '0005_remove_morbilidademergencia_morbilidad__especia_aa4777_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='morbilidademergencia',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='morbilidadespecialista',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='pacientenoasistido',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
