# Generated by Django 4.2.28 on 2026-04-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencias', '0006_morbilidademergencia_activo_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='morbilidademergencia',
            index=models.Index(fields=['activo', '-created_at'], name='morbilidad__activo_00c535_idx'),
        ),
        migrations.AddIndex(
            model_name='morbilidademergencia',
            index=models.Index(fields=['activo', 'fecha_diagnostico'], name='morbilidad__activo_6a3aae_idx'),
        ),
        migrations.AddIndex(
            model_name='morbilidadespecialista',
            index=models.Index(fields=['activo', '-created_at'], name='morbilidad__activo_630d91_idx'),
        ),
        migrations.AddIndex(
            model_name='pacientenoasistido',
            index=models.Index(fields=['activo', '-created_at'], name='pacientes_n_activo_8edec6_idx'),
        ),
        migrations.AddIndex(
            model_name='pacientenoasistido',
            index=models.Index(fields=['activo', 'fecha_cita'], name='pacientes_n_activo_2e0fb1_idx'),
        ),
    ]
