# Generated by Django 4.2.30 on 2026-05-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencias', '0007_morbilidademergencia_morbilidad__activo_00c535_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='morbilidademergencia',
            name='diagnostico',
            field=models.TextField(blank=True, default='', verbose_name='Diagnóstico'),
        ),
    ]
