# Generated by Django 5.2.9 on 2026-02-18 00:31

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('ESPECIALISTA', 'Especialista'), ('PUBLICO', 'Público')], default='PUBLICO', max_length=20, verbose_name='Rol')),
                ('is_locked', models.BooleanField(default=False, verbose_name='Cuenta bloqueada')),
                ('failed_attempts', models.IntegerField(default=0, verbose_name='Intentos fallidos')),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='Código OTP')),
                ('otp_expiry', models.DateTimeField(blank=True, null=True, verbose_name='Expiración OTP')),
                ('otp_secret', models.CharField(blank=True, default='', max_length=32, verbose_name='Secreto OTP')),
                ('telefono', models.CharField(blank=True, default='', max_length=20, verbose_name='Teléfono')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BitacoraAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('LOGIN_FALLIDO', 'Intento de login fallido'), ('CUENTA_BLOQUEADA', 'Cuenta bloqueada'), ('CUENTA_DESBLOQUEADA', 'Cuenta desbloqueada'), ('CREAR', 'Creación de registro'), ('EDITAR', 'Edición de registro'), ('ELIMINAR', 'Eliminación de registro'), ('ACCESO_DENEGADO', 'Acceso denegado'), ('CAMBIO_PASSWORD', 'Cambio de contraseña'), ('VERIFICACION_2FA', 'Verificación 2FA'), ('EXPORTAR', 'Exportación de datos')], max_length=30, verbose_name='Acción')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('modulo', models.CharField(blank=True, default='', max_length=100, verbose_name='Módulo')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User Agent')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacora', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Bitácora de Auditoría',
                'db_table': 'bitacora_auditoria',
                'ordering': ['-fecha_hora'],
                'managed': True,
            },
        ),
    ]
