# Generated by Django 4.2.28 on 2026-02-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Cuenta verificada (2FA)'),
        ),
    ]
