# Generated by Django 5.2.9 on 2026-02-18 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('especialistas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_entrada', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Entrada')),
                ('hora_salida', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Salida')),
                ('pausa_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Inicio de Pausa')),
                ('pausa_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fin de Pausa')),
                ('total_horas', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Total Horas')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('especialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jornadas', to='especialistas.especialista', verbose_name='Especialista')),
            ],
            options={
                'verbose_name': 'Jornada',
                'verbose_name_plural': 'Jornadas',
                'db_table': 'jornadas',
                'ordering': ['-fecha', '-hora_entrada'],
            },
        ),
    ]
