# Generated by Django 4.2.28 on 2026-04-15 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_mov', models.CharField(choices=[('emergencia', 'Emergencia'), ('especialista', 'Especialista'), ('ecosonograma', 'Ecosonograma'), ('no_asistido', 'No Asistido')], max_length=20, verbose_name='Tipo de Movimiento')),
                ('nombre_display', models.CharField(max_length=255, verbose_name='Nombre de Paciente')),
                ('detalle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Detalles Adicionales')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Registro')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_generados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['activo', 'created_at'], name='reportes_mo_activo_b137ef_idx'), models.Index(fields=['tipo_mov'], name='reportes_mo_tipo_mo_f04760_idx'), models.Index(fields=['content_type', 'object_id'], name='reportes_mo_content_0c1724_idx')],
            },
        ),
    ]
