# Generated by Django 4.2.28 on 2026-04-28 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='tipo_mov',
            field=models.CharField(choices=[('emergencia', 'Emergencia'), ('especialista', 'Especialista'), ('ecosonograma', 'Ecosonograma'), ('no_asistido', 'Paciente no asistido de Especialistas')], max_length=20, verbose_name='Tipo de Movimiento'),
        ),
        migrations.CreateModel(
            name='CierreMes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveIntegerField()),
                ('anio', models.PositiveIntegerField()),
                ('fecha_cierre', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Cierre')),
                ('total_registros', models.IntegerField(default=0)),
                ('usuario_cierre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cierres_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cierre de Mes',
                'verbose_name_plural': 'Cierres de Meses',
                'ordering': ['-anio', '-mes'],
                'unique_together': {('mes', 'anio')},
            },
        ),
    ]
