# Generated by Django 4.2.30 on 2026-09-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_alter_movimiento_tipo_mov_cierremes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='movimiento',
            name='reportes_mo_tipo_mo_f04760_idx',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='tipo_mov',
        ),
        migrations.AddField(
            model_name='movimiento',
            name='accion',
            field=models.CharField(choices=[('CREAR', 'Crear'), ('EDITAR', 'Editar'), ('ELIMINAR', 'Eliminar')], default='CREAR', max_length=20, verbose_name='Acción Realizada'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='modulo_origen',
            field=models.CharField(choices=[('EMERGENCIA', 'Emergencia'), ('CONSULTA_ESPECIALISTA', 'Consulta Especialista'), ('ECOSONOGRAMA', 'Ecosonograma'), ('NO_ASISTIDO', 'No Asistido')], default='EMERGENCIA', max_length=30, verbose_name='Módulo Origen'),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['accion'], name='reportes_mo_accion_766364_idx'),
        ),
    ]
